### ISSUE TITLE
데이터베이스 구조 변경

### ISSUE THREAD

**Issue by gilteunchoi** [Pusan21/Elecvery-Clone-Backend#10]
## 사전 수행 이슈

- 없음

## 이슈 내용

Database 구조 변경

```java
@Entity
@Getter
public class Member_Station {}
```

## TODO

- [x] 유저, 관리자 테이블 합치기 
- [x] 유저 - 충전소 M:N 관계로 구성하기

**Comment by shkisme** [comment]
@gilteunchoi 유저와 관리자 테이블이 합쳐진 후에 API 개발을 하는 것이 좋을까요?

**Comment by gilteunchoi** [comment]
충전소 관련된 내용부터 API 개발시작하면 될 것 같아요
