### ISSUE TITLE
더미 데이터가 중복으로 생성되는 문제

### ISSUE THREAD

**Issue by shkisme** [Pusan21/Elecvery-Clone-Backend#29]
## 이슈 내용

member dummy data를 생성하는 test 코드를 돌렸을 때, 다음과 같은 결과가 나오는 것을 확인했습니다. 수정해야 할 부분 같습니다!

![image](https://user-images.githubusercontent.com/92802207/198678812-c22def8d-1498-42ab-9953-4c1e97fa53a1.png)

또 개인적으로 왜 이런 현상이 발생하는지 궁금합니다.

**Comment by fienestar** [comment]
현재 생성자가 아닌 GeneratedValue 어노테이션을 통해 데이터를 초기화하고 있습니다. 또, 이는 생성되는 id가 예측가능하다는 점에서 보안 문제를 겪을 수 있습니다(1,2,3..) 멤버가 존재하지 않는다면 생성하고, 예측하기 어려운 값으로 생성해야합니다.
