### ISSUE TITLE
테스트간 데이터 의존성 문제

### ISSUE THREAD

**Issue by fienestar** [Pusan21/Elecvery-Clone-Backend#31]
## 이슈 내용

https://stackoverflow.com/a/9529014
에 따르면 테스트의 순서를 지정할 수 있으나, 테스트는 그 자체로 독립적인게 좋습니다.
또, 현재처럼 작성하는 경우 보장되지 않는 것 같습니다.

즉, 테스트에 필요한 데이터는 해당 테스트에서 생성해야하며, 완료후 삭제해야할 것 같습니다.

현재 PaymentInformationRepositoryTest는 MemberDummyTest에 의존하는 것으로 보입니다.

**Comment by shkisme** [comment]
그렇군요! 새롭게 알아갑니다. 테스트 시작할 때 더미데이터를 생성하고, 테스트가 끝나면 삭제하는 방향으로 수정하겠습니다👍
