### ISSUE TITLE
README 작성

### ISSUE THREAD

**Issue by gilteunchoi** [Pusan21/Elecvery-Clone-Backend#5]
- [x] 개발 환경 구성 정리
- [x] git clone, 프로젝트 build 과정 설명 작성
- [x] 노션 및 API 문서 연결
- [x] 이슈 라벨 정리

**Comment by shkisme** [comment]
이슈 라벨 정리 완료했습니다

**Comment by shkisme** [comment]
`Project` 만들어 두었고, 이슈와 PR 모두 등록해두었습니다.
`Milestone`은 아직 어떤 방식으로 사용하는지 모르겠네요..
